### ISSUE TITLE
PMC6607402 used DAVID 6.7

### ISSUE THREAD

**Issue by markziemann** [markziemann/enrichment_recipe#22]
As they used version 6.7, we should replicate with 6.7 as well.

**Comment by anusuiyaxbora** [comment]
I tried accessing v6.7 but it looks like people are not able to access v6.8 itself... I will search more if I can access v6.7 again.

**Comment by anusuiyaxbora** [comment]
Yes true! Some articles have probably used v6.7 too... If I am not wrong, v6.8 was available since 2016 and v6.7 itself retired in Oct 2020, so there are chances that articles have used either of those versions. There are no mentions of the versions in most of the papers... but for us, we didn't have access to v6.7...

**Comment by markziemann** [comment]
Thanks I have added a note to say that 6.7 isn't available and this is a limitation of our work
